on:
  push:
    branches:
      - test
    tags:
      - '*'

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_REPOSITORY }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      -
        name: Build image
        run: |
          ls -lsah
          pwd
          docker build . --file .docker/app/Dockerfile --tag $IMAGE_NAME
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:$VERSION
